basePath: /api
definitions:
  helper.HTTPError:
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  model.Departamento:
    properties:
      departamento:
        maxLength: 50
        type: string
    required:
    - departamento
    type: object
  model.DepartamentoDto:
    properties:
      departamento:
        example: Recursos Humanos
        type: string
      id:
        type: integer
    type: object
  model.Funcao:
    properties:
      funcao:
        maxLength: 50
        type: string
      id_departamento:
        minimum: 1
        type: integer
    required:
    - funcao
    - id_departamento
    type: object
  model.FuncaoDto:
    properties:
      cargo:
        type: string
      departamento:
        $ref: '#/definitions/model.DepartamentoDto'
      id:
        type: integer
    type: object
  model.Funcionario_Dto:
    properties:
      funcao:
        $ref: '#/definitions/model.FuncaoDto'
      id:
        type: integer
      matricula:
        type: string
      nome:
        type: string
    type: object
  model.FuncionarioINserir:
    properties:
      id_departamento:
        minimum: 1
        type: integer
      id_funcao:
        minimum: 1
        type: integer
      matricula:
        maxLength: 7
        minLength: 7
        type: string
      nome:
        maxLength: 150
        minLength: 3
        type: string
    required:
    - id_departamento
    - id_funcao
    - matricula
    - nome
    type: object
  model.UpdateFuncionarioRequest:
    properties:
      id_departamento:
        description: Ponteiro!
        type: integer
      id_funcao:
        description: Ponteiro!
        type: integer
      nome:
        description: Ponteiro! Se for nil, não atualiza
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: suporte@seusaas.com.br
    name: Suporte API
    url: http://www.seusaas.com.br
  description: API para gestão de EPIs.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: SaaS EPI API
  version: "1.0"
paths:
  /cadastro-departamento:
    post:
      consumes:
      - application/json
      description: Cadastra um novo departamento no sistema
      parameters:
      - description: Dados do departamento
        in: body
        name: departamento
        required: true
        schema:
          $ref: '#/definitions/model.Departamento'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Dados inválidos
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "409":
          description: Departamento já existe
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Criar novo departamento
      tags:
      - Departamentos
  /cadastro-funcao:
    post:
      consumes:
      - application/json
      description: Cadastra uma nova funcao no sistema
      parameters:
      - description: Dados da funcao
        in: body
        name: funcao
        required: true
        schema:
          $ref: '#/definitions/model.Funcao'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Dados inválidos
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "409":
          description: id de departamento nao existe no sistema
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Criar uma funcao
      tags:
      - funcao
  /cadastro-funcionario:
    post:
      consumes:
      - application/json
      description: Cadastra um novo funcionario no sistema
      parameters:
      - description: Dados do funcionario
        in: body
        name: funcionario
        required: true
        schema:
          $ref: '#/definitions/model.FuncionarioINserir'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Dados inválidos
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "409":
          description: Departamento já existe
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Cadastrar novo funcionarios
      tags:
      - funcionarios
  /departamento/{id}:
    delete:
      description: Remove (ou inativa) um departamento pelo ID
      parameters:
      - description: ID do Departamento
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Sem Conteúdo (Sucesso)
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Deletar departamento
      tags:
      - Departamentos
  /departamentos:
    get:
      description: Retorna uma lista com todos os departamentos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.DepartamentoDto'
            type: array
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Listar todos
      tags:
      - Departamentos
  /departamentos/{id}:
    get:
      description: Retorna os detalhes de um único departamento
      parameters:
      - description: ID do Departamento
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.DepartamentoDto'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Buscar por ID
      tags:
      - Departamentos
    put:
      consumes:
      - application/json
      description: Atualiza o nome de um departamento existente
      parameters:
      - description: ID do Departamento
        in: path
        name: id
        required: true
        type: integer
      - description: Novo nome
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Departamento'
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erro de validação (ID ou Nome curto)
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      summary: Atualizar departamento
      tags:
      - Departamentos
  /funcao/{id}:
    delete:
      description: Remove (ou inativa) uma funcao pelo ID
      parameters:
      - description: ID da funcao
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Sem Conteúdo (Sucesso)
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Deletar funcao
      tags:
      - funcao
    get:
      description: Retorna os detalhes de uma unica funcao
      parameters:
      - description: ID da funcao
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.FuncaoDto'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Buscar por ID
      tags:
      - funcao
    put:
      consumes:
      - application/json
      description: Atualiza o nome de uma funcao e seu departamento existente
      parameters:
      - description: ID da funcao
        in: path
        name: id
        required: true
        type: integer
      - description: Novo nome
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.Funcao'
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erro de validação (ID ou Nome curto)
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      summary: Atualizar funcao
      tags:
      - funcao
  /funcionario/{id}:
    delete:
      description: Remove (ou inativa) um funcionario pelo ID
      parameters:
      - description: ID do funcionario
        in: path
        name: id
        required: true
        type: integer
      responses:
        "204":
          description: Sem Conteúdo (Sucesso)
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Deletar funcionario
      tags:
      - funcionarios
    patch:
      consumes:
      - application/json
      description: Atualiza os dados de um funcionario existente
      parameters:
      - description: ID do funcionario
        in: path
        name: id
        required: true
        type: integer
      - description: funcionario novos dados
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/model.UpdateFuncionarioRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Sucesso
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Erro de validação (ID ou Nome curto)
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      summary: Atualizar funcionario
      tags:
      - funcionarios
  /funcionario/{matricula}:
    get:
      description: Retorna os detalhes de um único funcionario
      parameters:
      - description: matricula do funcionario
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Funcionario_Dto'
        "400":
          description: ID inválido
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "404":
          description: Não encontrado
          schema:
            $ref: '#/definitions/helper.HTTPError'
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Buscar por matricula
      tags:
      - funcionarios
  /funcionarios:
    get:
      description: Retorna uma lista com todos os funcionarios
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Funcionario_Dto'
            type: array
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Listar todos
      tags:
      - funcionarios
  /funcoes:
    get:
      description: Retorna uma lista com todos os funcoes
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.FuncaoDto'
            type: array
        "500":
          description: Erro interno
          schema:
            $ref: '#/definitions/helper.HTTPError'
      security:
      - BearerAuth: []
      summary: Listar todos
      tags:
      - funcao
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
